package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/1kyryll/go-grpc/internal/common/gen/orders"
	"github.com/1kyryll/go-grpc/internal/common/gen/user"
	"github.com/1kyryll/go-grpc/internal/common/sqlc"
	"github.com/1kyryll/go-grpc/internal/middleware"
	"github.com/1kyryll/go-grpc/internal/services/gateway/graph/model"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	phone := ""
	if input.Phone != nil {
		phone = *input.Phone
	}

	resp, err := r.userGrpcClient.Register(ctx, &user.RegisterRequest{
		Username: input.Username,
		Email:    input.Email,
		Password: input.Password,
		Phone:    phone,
	})
	if err != nil {
		return nil, fmt.Errorf("registration failed: %w", err)
	}

	var phonePtr *string
	if resp.User.Phone != "" {
		phonePtr = &resp.User.Phone
	}

	return &model.AuthResponse{
		AuthToken: &model.AuthToken{
			AccessToken: resp.AccessToken,
			ExpiredAt:   time.Unix(resp.ExpiredAt, 0),
		},
		User: &model.User{
			ID:       fmt.Sprintf("%d", resp.User.Id),
			Username: resp.User.Username,
			Email:    resp.User.Email,
			Phone:    phonePtr,
			Role:     resp.User.Role,
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	resp, err := r.userGrpcClient.Login(ctx, &user.LoginRequest{
		Username: input.Username,
		Password: input.Password,
	})
	if err != nil {
		return nil, fmt.Errorf("login failed: %w", err)
	}

	var phonePtr *string
	if resp.User.Phone != "" {
		phonePtr = &resp.User.Phone
	}

	return &model.AuthResponse{
		AuthToken: &model.AuthToken{
			AccessToken: resp.AccessToken,
			ExpiredAt:   time.Unix(resp.ExpiredAt, 0),
		},
		User: &model.User{
			ID:       fmt.Sprintf("%d", resp.User.Id),
			Username: resp.User.Username,
			Email:    resp.User.Email,
			Phone:    phonePtr,
			Role:     resp.User.Role,
		},
	}, nil
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.CreateOrderPayload, error) {
	var validationErrors []*model.ValidationError

	if len(input.Items) == 0 {
		validationErrors = append(validationErrors, &model.ValidationError{
			Field:   "items",
			Message: "at least one item is required",
		})
	}

	authUser, err := middleware.RequireRole(ctx, middleware.RoleCustomer)
	if err != nil {
		return nil, err
	}
	if input.UserID != authUser.ID {
		return nil, fmt.Errorf("Cannot create orders for other Users")
	}

	userID, err := strconv.Atoi(input.UserID)
	if err != nil {
		validationErrors = append(validationErrors, &model.ValidationError{
			Field:   "userId",
			Message: "invalid user ID",
		})
	}

	for i, item := range input.Items {
		if item.Quantity <= 0 {
			validationErrors = append(validationErrors, &model.ValidationError{
				Field:   fmt.Sprintf("items[%d].quantity", i),
				Message: "quantity must be greater than 0",
			})
		}

		menuItemID, err := strconv.Atoi(item.MenuItemID)
		if err != nil {
			validationErrors = append(validationErrors, &model.ValidationError{
				Field:   fmt.Sprintf("items[%d].menuItemId", i),
				Message: "invalid menu item ID",
			})
			continue
		}

		dbItem, err := r.queries.GetMenuItemByID(ctx, int32(menuItemID))
		if err != nil {
			validationErrors = append(validationErrors, &model.ValidationError{
				Field:   fmt.Sprintf("items[%d].menuItemId", i),
				Message: fmt.Sprintf("menu item %d not found", menuItemID),
			})
			continue
		}
		if dbItem.IsAvailable.Valid && !dbItem.IsAvailable.Bool {
			validationErrors = append(validationErrors, &model.ValidationError{
				Field:   fmt.Sprintf("items[%d].menuItemId", i),
				Message: fmt.Sprintf("menu item '%s' is not available", dbItem.Name),
			})
		}
	}

	if len(validationErrors) > 0 {
		return &model.CreateOrderPayload{Errors: validationErrors}, nil
	}

	grpcItems := make([]*orders.OrderItemInput, len(input.Items))
	for i, item := range input.Items {
		menuItemID, _ := strconv.Atoi(item.MenuItemID)
		specialInstructions := ""
		if item.SpecialInstructions != nil {
			specialInstructions = *item.SpecialInstructions
		}
		grpcItems[i] = &orders.OrderItemInput{
			MenuItemId:          int32(menuItemID),
			Quantity:            int32(item.Quantity),
			SpecialInstructions: specialInstructions,
		}
	}

	_, err = r.grpcClient.CreateOrder(ctx, &orders.CreateOrderRequest{
		CustomerId: int32(userID),
		Items:      grpcItems,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create order via gRPC: %w", err)
	}

	dbOrders, err := r.queries.GetOrders(ctx, int32(userID))
	if err != nil {
		return nil, fmt.Errorf("failed to fetch created order: %w", err)
	}
	if len(dbOrders) == 0 {
		return nil, fmt.Errorf("order created but not found")
	}

	latest := dbOrders[len(dbOrders)-1]
	order := mapOrder(latest)

	r.broadcastNewOrder(order)

	return &model.CreateOrderPayload{Order: order}, nil
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	if _, err := middleware.RequireRole(ctx, middleware.RoleKitchenStaff); err != nil {
		return nil, err
	}

	orderID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	dbOrder, err := r.queries.UpdateOrderStatus(ctx, sqlc.UpdateOrderStatusParams{
		ID:     orderID,
		Status: status.String(),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update order status: %w", err)
	}

	order := mapOrder(dbOrder)
	r.broadcastStatusChange(order)
	return order, nil
}

// CompleteOrder is the resolver for the completeOrder field.
func (r *mutationResolver) CompleteOrder(ctx context.Context, orderID string) (*model.Order, error) {
	if _, err := middleware.RequireRole(ctx, middleware.RoleKitchenStaff); err != nil {
		return nil, err
	}

	id, err := parseID(orderID)
	if err != nil {
		return nil, err
	}

	if err := r.queries.CompleteTicketByOrderID(ctx, id); err != nil {
		return nil, fmt.Errorf("failed to complete ticket: %w", err)
	}
	if err := r.queries.CompleteOrder(ctx, id); err != nil {
		return nil, fmt.Errorf("failed to complete order: %w", err)
	}

	dbOrder, err := r.queries.GetOrderByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch completed order: %w", err)
	}

	order := mapOrder(dbOrder)
	r.broadcastStatusChange(order)
	return order, nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (*model.Order, error) {
	if _, err := middleware.RequireRole(ctx, middleware.RoleCustomer); err != nil {
		return nil, err
	}

	id, err := parseID(orderID)
	if err != nil {
		return nil, err
	}

	dbOrder, err := r.queries.CancelOrder(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("failed to cancel order: %w", err)
	}

	order := mapOrder(dbOrder)
	r.broadcastStatusChange(order)
	return order, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
