package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/1kyryll/go-grpc/internal/services/common/sqlc"
	"github.com/1kyryll/go-grpc/internal/services/gateway/dataloaders"
	"github.com/1kyryll/go-grpc/internal/services/gateway/graph/model"
)

// ─── Customer Type Resolver ─────────────────────────────────────────────────

// Orders is the resolver for the orders field.
func (r *customerResolver) Orders(ctx context.Context, obj *model.Customer, first *int, after *string) (*model.OrderConnection, error) {
	customerID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}

	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}

	var afterID int32
	if after != nil {
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, err
		}
	}

	rows, err := r.queries.GetOrdersByCustomerIDPaginated(ctx, sqlc.GetOrdersByCustomerIDPaginatedParams{
		CustomerID: customerID,
		AfterID:    afterID,
		PageLimit:  limit + 1,
	})
	if err != nil {
		return nil, fmt.Errorf("fetching customer orders: %w", err)
	}

	hasNext := len(rows) > int(limit)
	if hasNext {
		rows = rows[:limit]
	}

	edges := make([]*model.OrderEdge, len(rows))
	for i, row := range rows {
		edges[i] = &model.OrderEdge{
			Cursor: encodeCursor(row.ID),
			Node:   mapOrder(row),
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	totalCount, err := r.queries.CountOrdersByCustomerID(ctx, customerID)
	if err != nil {
		return nil, fmt.Errorf("counting customer orders: %w", err)
	}

	return &model.OrderConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: afterID > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int(totalCount),
	}, nil
}

// ─── Mutation Resolver ──────────────────────────────────────────────────────

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.CreateOrderPayload, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: UpdateOrderStatus - updateOrderStatus"))
}

// CompleteOrder is the resolver for the completeOrder field.
func (r *mutationResolver) CompleteOrder(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CompleteOrder - completeOrder"))
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CancelOrder - cancelOrder"))
}

// ─── Order Type Resolver ────────────────────────────────────────────────────

// Customer is the resolver for the customer field.
func (r *orderResolver) Customer(ctx context.Context, obj *model.Order) (*model.Customer, error) {
	c, err := dataloaders.For(ctx).CustomerByID.Load(ctx, obj.CustomerID)
	if err != nil {
		return nil, fmt.Errorf("loading customer %d: %w", obj.CustomerID, err)
	}
	return mapCustomer(c), nil
}

// Items is the resolver for the items field.
func (r *orderResolver) Items(ctx context.Context, obj *model.Order) ([]*model.OrderItem, error) {
	orderID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}

	rows, err := dataloaders.For(ctx).OrderItemsByOrderID.Load(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("loading order items for order %s: %w", obj.ID, err)
	}

	items := make([]*model.OrderItem, len(rows))
	for i, row := range rows {
		items[i] = &model.OrderItem{
			ID:                  fmt.Sprintf("%d", row.ID),
			MenuItemID:          row.MenuItemID,
			Quantity:            int(row.Quantity),
			SpecialInstructions: model.TextToStringPtr(row.SpecialInstructions),
		}
	}
	return items, nil
}

// Ticket is the resolver for the ticket field.
func (r *orderResolver) Ticket(ctx context.Context, obj *model.Order) (*model.Ticket, error) {
	orderID, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}

	t, err := dataloaders.For(ctx).TicketByOrderID.Load(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("loading ticket for order %s: %w", obj.ID, err)
	}
	if t == nil {
		return nil, nil
	}

	return &model.Ticket{
		ID:        fmt.Sprintf("%d", t.ID),
		OrderID:   t.OrderID,
		Status:    model.TicketStatus(t.Status),
		CreatedAt: model.TimestampToTime(t.CreatedAt),
		UpdatedAt: model.TimestampToTime(t.UpdatedAt),
	}, nil
}

// TotalPrice is the resolver for the totalPrice field.
func (r *orderResolver) TotalPrice(ctx context.Context, obj *model.Order) (float64, error) {
	orderID, err := parseID(obj.ID)
	if err != nil {
		return 0, err
	}

	rows, err := dataloaders.For(ctx).OrderItemsByOrderID.Load(ctx, orderID)
	if err != nil {
		return 0, fmt.Errorf("loading items for total price of order %s: %w", obj.ID, err)
	}

	var total float64
	for _, item := range rows {
		mi, err := dataloaders.For(ctx).MenuItemByID.Load(ctx, item.MenuItemID)
		if err != nil {
			return 0, fmt.Errorf("loading menu item %d: %w", item.MenuItemID, err)
		}
		price, _ := mi.Price.Float64Value()
		total += price.Float64 * float64(item.Quantity)
	}
	return total, nil
}

// ─── OrderItem Type Resolver ────────────────────────────────────────────────

// MenuItem is the resolver for the menuItem field.
func (r *orderItemResolver) MenuItem(ctx context.Context, obj *model.OrderItem) (model.MenuItem, error) {
	mi, err := dataloaders.For(ctx).MenuItemByID.Load(ctx, obj.MenuItemID)
	if err != nil {
		return nil, fmt.Errorf("loading menu item %d: %w", obj.MenuItemID, err)
	}
	return model.MapMenuItem(mi), nil
}

// Subtotal is the resolver for the subtotal field.
func (r *orderItemResolver) Subtotal(ctx context.Context, obj *model.OrderItem) (float64, error) {
	mi, err := dataloaders.For(ctx).MenuItemByID.Load(ctx, obj.MenuItemID)
	if err != nil {
		return 0, fmt.Errorf("loading menu item %d for subtotal: %w", obj.MenuItemID, err)
	}
	price, _ := mi.Price.Float64Value()
	return price.Float64 * float64(obj.Quantity), nil
}

// ─── Query Resolver ─────────────────────────────────────────────────────────

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	orderID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	row, err := r.queries.GetOrderByID(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("order %s not found: %w", id, err)
	}

	return mapOrder(row), nil
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, first *int, after *string, status *model.OrderStatus) (*model.OrderConnection, error) {
	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}

	var afterID int32
	var err error
	if after != nil {
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, err
		}
	}

	var statusStr string
	if status != nil {
		statusStr = status.String()
	}

	rows, err := r.queries.GetOrdersPaginated(ctx, sqlc.GetOrdersPaginatedParams{
		AfterID:   afterID,
		Status:    statusStr,
		PageLimit: limit + 1,
	})
	if err != nil {
		return nil, fmt.Errorf("fetching orders: %w", err)
	}

	hasNext := len(rows) > int(limit)
	if hasNext {
		rows = rows[:limit]
	}

	edges := make([]*model.OrderEdge, len(rows))
	for i, row := range rows {
		edges[i] = &model.OrderEdge{
			Cursor: encodeCursor(row.ID),
			Node:   mapOrder(row),
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	totalCount, err := r.queries.CountOrders(ctx, statusStr)
	if err != nil {
		return nil, fmt.Errorf("counting orders: %w", err)
	}

	return &model.OrderConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: afterID > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int(totalCount),
	}, nil
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	customerID, err := parseID(id)
	if err != nil {
		return nil, err
	}

	row, err := r.queries.GetCustomerByID(ctx, customerID)
	if err != nil {
		return nil, fmt.Errorf("customer %s not found: %w", id, err)
	}

	return mapCustomer(row), nil
}

// MenuItems is the resolver for the menuItems field.
func (r *queryResolver) MenuItems(ctx context.Context, first *int, after *string, category *model.MenuCategory) (*model.MenuItemConnection, error) {
	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}

	var afterID int32
	var err error
	if after != nil {
		afterID, err = decodeCursor(*after)
		if err != nil {
			return nil, err
		}
	}

	var categoryStr string
	if category != nil {
		categoryStr = category.String()
	}

	rows, err := r.queries.GetMenuItemsPaginated(ctx, sqlc.GetMenuItemsPaginatedParams{
		AfterID:   afterID,
		Category:  categoryStr,
		PageLimit: limit + 1,
	})
	if err != nil {
		return nil, fmt.Errorf("fetching menu items: %w", err)
	}

	hasNext := len(rows) > int(limit)
	if hasNext {
		rows = rows[:limit]
	}

	edges := make([]*model.MenuItemEdge, len(rows))
	for i, row := range rows {
		edges[i] = &model.MenuItemEdge{
			Cursor: encodeCursor(row.ID),
			Node:   model.MapMenuItem(row),
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	totalCount, err := r.queries.CountMenuItems(ctx, categoryStr)
	if err != nil {
		return nil, fmt.Errorf("counting menu items: %w", err)
	}

	return &model.MenuItemConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: afterID > 0,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: int(totalCount),
	}, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	searchTerm := model.StringToText(query)

	var results []model.SearchResult

	// Search menu items
	menuItems, err := r.queries.SearchMenuItems(ctx, searchTerm)
	if err != nil {
		return nil, fmt.Errorf("searching menu items: %w", err)
	}
	for _, item := range menuItems {
		results = append(results, model.MapMenuItem(item).(model.SearchResult))
	}

	// Search customers
	customers, err := r.queries.SearchCustomers(ctx, searchTerm)
	if err != nil {
		return nil, fmt.Errorf("searching customers: %w", err)
	}
	for _, c := range customers {
		results = append(results, mapCustomer(c))
	}

	// Search orders
	orders, err := r.queries.SearchOrders(ctx, searchTerm)
	if err != nil {
		return nil, fmt.Errorf("searching orders: %w", err)
	}
	for _, o := range orders {
		results = append(results, mapOrder(o))
	}

	return results, nil
}

// ─── Subscription Resolver ──────────────────────────────────────────────────

// OrderCreated is the resolver for the orderCreated field.
func (r *subscriptionResolver) OrderCreated(ctx context.Context) (<-chan *model.Order, error) {
	panic(fmt.Errorf("not implemented: OrderCreated - orderCreated"))
}

// OrderStatusChanged is the resolver for the orderStatusChanged field.
func (r *subscriptionResolver) OrderStatusChanged(ctx context.Context, orderID *string) (<-chan *model.Order, error) {
	panic(fmt.Errorf("not implemented: OrderStatusChanged - orderStatusChanged"))
}

// ─── Ticket Type Resolver ───────────────────────────────────────────────────

// Order is the resolver for the order field.
func (r *ticketResolver) Order(ctx context.Context, obj *model.Ticket) (*model.Order, error) {
	row, err := r.queries.GetOrderByID(ctx, obj.OrderID)
	if err != nil {
		return nil, fmt.Errorf("loading order %d for ticket: %w", obj.OrderID, err)
	}
	return mapOrder(row), nil
}

// Customer returns CustomerResolver implementation.
func (r *Resolver) Customer() CustomerResolver { return &customerResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Ticket returns TicketResolver implementation.
func (r *Resolver) Ticket() TicketResolver { return &ticketResolver{r} }

type customerResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type ticketResolver struct{ *Resolver }
