package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"

	"github.com/1kyryll/go-grpc/internal/services/gateway/graph/model"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input model.CreateOrderInput) (*model.CreateOrderPayload, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id string, status model.OrderStatus) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: UpdateOrderStatus - updateOrderStatus"))
}

// CompleteOrder is the resolver for the completeOrder field.
func (r *mutationResolver) CompleteOrder(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CompleteOrder - completeOrder"))
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, orderID string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CancelOrder - cancelOrder"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id string) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, first *int, after *string, status *model.OrderStatus) (*model.OrderConnection, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, id string) (*model.Customer, error) {
	panic(fmt.Errorf("not implemented: Customer - customer"))
}

// MenuItems is the resolver for the menuItems field.
func (r *queryResolver) MenuItems(ctx context.Context, first *int, after *string, category *model.MenuCategory) (*model.MenuItemConnection, error) {
	panic(fmt.Errorf("not implemented: MenuItems - menuItems"))
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	panic(fmt.Errorf("not implemented: Search - search"))
}

// OrderCreated is the resolver for the orderCreated field.
func (r *subscriptionResolver) OrderCreated(ctx context.Context) (<-chan *model.Order, error) {
	panic(fmt.Errorf("not implemented: OrderCreated - orderCreated"))
}

// OrderStatusChanged is the resolver for the orderStatusChanged field.
func (r *subscriptionResolver) OrderStatusChanged(ctx context.Context, orderID *string) (<-chan *model.Order, error) {
	panic(fmt.Errorf("not implemented: OrderStatusChanged - orderStatusChanged"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
