// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type MenuItem interface {
	IsMenuItem()
	GetID() string
	GetName() string
	GetDescription() *string
	GetPrice() float64
	GetCategory() MenuCategory
	GetIsAvailable() bool
}

type SearchResult interface {
	IsSearchResult()
}

type AuthResponse struct {
	AuthToken *AuthToken `json:"authToken"`
	User      *User      `json:"user"`
}

type AuthToken struct {
	AccessToken string    `json:"accessToken"`
	ExpiredAt   time.Time `json:"expiredAt"`
}

type CreateOrderInput struct {
	UserID string            `json:"userId"`
	Items  []*OrderItemInput `json:"items"`
}

type CreateOrderPayload struct {
	Order  *Order             `json:"order,omitempty"`
	Errors []*ValidationError `json:"errors,omitempty"`
}

type DrinkItem struct {
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Description *string      `json:"description,omitempty"`
	Price       float64      `json:"price"`
	Category    MenuCategory `json:"category"`
	IsAvailable bool         `json:"isAvailable"`
	IsAlcoholic bool         `json:"isAlcoholic"`
}

func (DrinkItem) IsMenuItem()                    {}
func (this DrinkItem) GetID() string             { return this.ID }
func (this DrinkItem) GetName() string           { return this.Name }
func (this DrinkItem) GetDescription() *string   { return this.Description }
func (this DrinkItem) GetPrice() float64         { return this.Price }
func (this DrinkItem) GetCategory() MenuCategory { return this.Category }
func (this DrinkItem) GetIsAvailable() bool      { return this.IsAvailable }

func (DrinkItem) IsSearchResult() {}

type FoodItem struct {
	ID                string       `json:"id"`
	Name              string       `json:"name"`
	Description       *string      `json:"description,omitempty"`
	Price             float64      `json:"price"`
	Category          MenuCategory `json:"category"`
	IsAvailable       bool         `json:"isAvailable"`
	ContainsAllergens []string     `json:"containsAllergens,omitempty"`
}

func (FoodItem) IsMenuItem()                    {}
func (this FoodItem) GetID() string             { return this.ID }
func (this FoodItem) GetName() string           { return this.Name }
func (this FoodItem) GetDescription() *string   { return this.Description }
func (this FoodItem) GetPrice() float64         { return this.Price }
func (this FoodItem) GetCategory() MenuCategory { return this.Category }
func (this FoodItem) GetIsAvailable() bool      { return this.IsAvailable }

func (FoodItem) IsSearchResult() {}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type MenuItemConnection struct {
	Edges      []*MenuItemEdge `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type MenuItemEdge struct {
	Cursor string   `json:"cursor"`
	Node   MenuItem `json:"node"`
}

type Mutation struct {
}

type OrderConnection struct {
	Edges      []*OrderEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type OrderEdge struct {
	Cursor string `json:"cursor"`
	Node   *Order `json:"node"`
}

type OrderItemInput struct {
	MenuItemID          string  `json:"menuItemId"`
	Quantity            int     `json:"quantity"`
	SpecialInstructions *string `json:"specialInstructions,omitempty"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type RegisterInput struct {
	Username string  `json:"username"`
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Phone    *string `json:"phone,omitempty"`
}

type Subscription struct {
}

type ValidationError struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

type MenuCategory string

const (
	MenuCategoryAppetizer MenuCategory = "APPETIZER"
	MenuCategoryMain      MenuCategory = "MAIN"
	MenuCategoryDrink     MenuCategory = "DRINK"
	MenuCategoryDessert   MenuCategory = "DESSERT"
)

var AllMenuCategory = []MenuCategory{
	MenuCategoryAppetizer,
	MenuCategoryMain,
	MenuCategoryDrink,
	MenuCategoryDessert,
}

func (e MenuCategory) IsValid() bool {
	switch e {
	case MenuCategoryAppetizer, MenuCategoryMain, MenuCategoryDrink, MenuCategoryDessert:
		return true
	}
	return false
}

func (e MenuCategory) String() string {
	return string(e)
}

func (e *MenuCategory) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MenuCategory(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MenuCategory", str)
	}
	return nil
}

func (e MenuCategory) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MenuCategory) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MenuCategory) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "PENDING"
	OrderStatusConfirmed OrderStatus = "CONFIRMED"
	OrderStatusCooking   OrderStatus = "COOKING"
	OrderStatusCompleted OrderStatus = "COMPLETED"
	OrderStatusCancelled OrderStatus = "CANCELLED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusConfirmed,
	OrderStatusCooking,
	OrderStatusCompleted,
	OrderStatusCancelled,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusConfirmed, OrderStatusCooking, OrderStatusCompleted, OrderStatusCancelled:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TicketStatus string

const (
	TicketStatusOpen    TicketStatus = "OPEN"
	TicketStatusCooking TicketStatus = "COOKING"
	TicketStatusDone    TicketStatus = "DONE"
)

var AllTicketStatus = []TicketStatus{
	TicketStatusOpen,
	TicketStatusCooking,
	TicketStatusDone,
}

func (e TicketStatus) IsValid() bool {
	switch e {
	case TicketStatusOpen, TicketStatusCooking, TicketStatusDone:
		return true
	}
	return false
}

func (e TicketStatus) String() string {
	return string(e)
}

func (e *TicketStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TicketStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TicketStatus", str)
	}
	return nil
}

func (e TicketStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TicketStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TicketStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
